### ISSUE TITLE
json-schema-generator skips some fields with primary goLang types

### ISSUE THREAD

**Issue by roytman** [fybrik/json-schema-generator#25]
In some scenarios see https://github.com/fybrik/fybrik/pull/1461#discussion_r869975120, some of the fields with primary goLang types are missing.

**Comment by roytman** [comment]
probably it works as expected, `FybrikApplicationSpec` is marked as `fybrik:validation:object="fybrik_application`, so json-schema-generator will generate JSON fail with it, and all related objects, except fields with goLang standard types. 
e.g. https://github.com/fybrik/fybrik/pull/1461/files#diff-6751dd64747f5b5ee5fbe12aa11868b9d7666d15c9b3564a6e68a34da27b4f06

packages under `pkg/model/` are marked with `fybrik:validation:schema`, so JSON objects in the generated files contain all fields.  e.g.  https://github.com/fybrik/fybrik/blob/f73d96379e279ac3823ba1f3e4f38d997e773334/charts/fybrik/files/taxonomy/datacatalog.json#L4

@Mohammad-nassar10 could you validate please if it is the right behavior?

**Comment by Mohammad-nassar10** [comment]
Right, the first use for `FybrikApplicationSpec` is used for types with specific mark (such as fybrikapplication and fybrikmodule). The second is used for packages with other specific mark (such as https://github.com/fybrik/fybrik/blob/f73d96379e279ac3823ba1f3e4f38d997e773334/pkg/model/datacatalog/doc.go#L5).

**Comment by roytman** [comment]
works as expected
